baseURL = "http://patrickrcallahan.com/dePoetisChristianis"
relativeURLs = true
languageCode = "en-us"
title = "Eschenbach's De Poetis Christianis Sacris"

[taxonomies]
  category = "categories"
  tag = "tags"
  poet = "poets"
  century = "centuries"
