#Name of action
name: hugo CI

#This makes the action trigger on any push to the master branch of the repository
on:
  push:
    branches: [ main ]

#This is the list of tasks that the action will execute.
#They will be executed in order an in an Ubuntu environment
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #This task checks out the git repository so it can be used by your action
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      #This task sets up hugo in the actions environment
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      #This task installs the dependencies required for the "Blist" theme
      - name: Install dependencies
        run: |
          npm install postcss -D
          npm install -g postcss-cli
          npm install -g autoprefixer
      #This task executes the hugo build command
      - name: Build
        run: hugo
      #This task pushes the build to the Front_End repository
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: PRoryCallahan/dePoetisChristianis
          publish_branch: master
          publish_dir: ./public
